### PR TITLE
Create Type Declarations

### PR DESCRIPTION
**Pull request by Preport**

### CODE REVIEW

**Comment by Preport** [comment]
Exporting the Type required might be a good idea as well.
i.e.: https://github.com/Preport/getBackpackTFListings/blob/main/types/tf2-sku-2/index.d.ts

**Comment by idinium96** [comment]
> Exporting the Type required might be a good idea as well.
> i.e.: https://github.com/Preport/getBackpackTFListings/blob/main/types/tf2-sku-2/index.d.ts

Yes, probably best to use this instead of converting it to class.

**Comment by Preport** [comment]
Usage Example
```ts
import sku from '.'

const randomVar = true, randomVar2 = true;
const myObj: sku = {
    defindex: 69,
    quality: 6
}
if (randomVar) myObj.effect = 420;
// The line below Will give error on IDE and tsc-compile
myObj.nonExistingValue = randomVar2

const skuStr = sku.fromObject(myObj);
```

**Comment by idinium96** [comment]
Thank you 💝

**Pull request merged**
